---
title: "play with rmd"
output: html_document
date: "2024-12-03"
---


```{r scatter}
plot(1:100)
```


```{r download}
download.file(url="https://raw.githubusercontent.com/cambiotraining/reproducibility-training/master/data/gapminder_data.csv", destfile="data/gapminder_data.csv")
```

```{r plot_hist}
## can label the chunck and go to specific chuncks bt the name
hist(rnorm(1000), col="red")
```


```{r load data}
#load tidyverse library
library(tidyverse) # used for data manipulation
library(rmarkdown) # used for paged_table function
library(kableExtra) # used for table
library(ggpubr) #used for ggarrange function 

#read file into R
pop_data <- read_csv("data/gapminder_data.csv")

#create a table with data from European countries in 2007 showing the countries 
#with the largest life expectancy at the top 
euro_data_tbl <- pop_data %>% 
                    filter(continent == "Europe" & year == 2007) %>% 
                    select(-continent, -year) %>% 
                    arrange(desc(lifeExp)) %>% 
                    rename(Country = country, "Population Size" = pop, 
                      "Life Expectancy" = lifeExp, "GDP" = gdpPercap)
```

```{r kbl}
euro_data_tbl %>% 
          kable(caption="European countries ordered by greatest life expectancy from 2007 data") %>% 
          kable_styling(bootstrap_options = "striped", full_width = F) %>% 
          scroll_box(width = "100%", height = "200px")
```


```{r paged-table}
paged_table(euro_data_tbl)
```


```{r}
euro_data_fig <- pop_data %>% 
                    filter(continent == "Europe") %>%
                    mutate(year=as_factor(year))
#Euro plot
euro_plot <- euro_data_fig %>%
                ggplot(mapping=aes(x=year, y=lifeExp)) +
                geom_violin() +
                stat_summary(fun.y = median, geom = "point")

#draw euro plot
euro_plot
```

